sudo: required
os:
  - linux
  - osx
  - windows

language: go
go:
 - tip

services:
 - docker

env:
- GOMAXPROCS=4 GORACE="halt_on_error=1"

before_install:
 - echo "$TRAVIS_GO_VERSION"
 - export PATH=/home/travis/gopath/bin:$PATH
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install bzr     ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install docker  ; fi

install:
 - go get ./...

script:
 - go test -race -timeout=90s ./...
